root = "."
testdata_dir = "testdata"
tmp_dir = ".build"

[build]
  args_bin = []
  bin = ".build\\main.exe"
  cmd = "go build -o ./.build/main.exe ./app/."
  delay = 1000
  exclude_dir = ["build"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "env", "development", "local", "production"]
  include_file = []
  kill_delay = "0s"
  log = "./.build/build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = "magenta"
  build = "magenta"
  main = "magenta"
  runner = "magenta"
  watcher = "magenta"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = true
  keep_scroll = true
